name: AI Deploy (production)
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'ai/**'

concurrency:
  group: ai_production_deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.actor == 'w7it'

    steps:
      - name: 💩 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: ./deploy.sh
